services:
  postgresql:
    container_name: postgresql_container
    image: bitnami/postgresql:15.4.0
    ports:
      - "5432:5432"
    networks:
      - batch_network
    volumes:
      - challenge_postgresql_data:/bitnami/postgresql
      - ./init-scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRESQL_USERNAME={CHANGE_ME}
      - POSTGRESQL_PASSWORD={CHANGE_ME}
      - POSTGRESQL_DATABASE=challenge
      - POSTGRESQL_POSTGRES_PASSWORD={CHANGE_ME} # Password of user "postgres"
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    ports:
      - "9000:9000"  # API S3
      - "9001:9001"  # MinIO Web Console
    environment:
      MINIO_ROOT_USER: {CHANGE_ME}
      MINIO_ROOT_PASSWORD: {CHANGE_ME}
    command: server --console-address ":9001" /data
    volumes:
      - challenge_minio_data:/data
  document-management-service:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: document_management_service
    depends_on:
      - postgresql
      - minio
    environment:
      - JAVA_OPTS=-Xmx50m -Xms50m
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/challenge
      - SPRING_DATASOURCE_USERNAME={CHANGE_ME}
      - SPRING_DATASOURCE_PASSWORD={CHANGE_ME}
      - MINIO_URL=http://minio:9000
      - MINIO_ACCESS_KEY={CHANGE_ME}
      - MINIO_SECRET_KEY={CHANGE_ME}
      - MINIO_BUCKET=document-bucket
    ports:
      - "8080:8080"
    networks:
      - batch_network
    deploy:
      resources:
        limits:
          memory: 50M

volumes:
  challenge_postgresql_data:
    driver: local
  challenge_minio_data:
    driver: local

networks:
  batch_network:
    driver: bridge
